services:
	weather-api:
		build: .
		container_name: server
		ports:
			- "8080:8080"
		volumes:
			- db:/app/db 
		networks:
			- custom_network  #Custom network name

networks:
	custom_network:  # Defining the custom network
		driver: bridge  #Bridge mode for isolated communication

